"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3

[[blocks]]
type = "rprompt"

  [[blocks.segments]]
  foreground = "#00C5C7"
  style = "plain"
  template = " {{ .CurrentDate | date .Format }} "
  type = "time"

    [blocks.segments.properties]
    time_format = "15:04:05"

[[blocks]]
alignment = "left"
type = "prompt"

  [[blocks.segments]]
  foreground = "#77E4F7"
  style = "plain"
  template = "{{ .Path }} "
  type = "path"

    [blocks.segments.properties]
    style = "full"

  [[blocks.segments]]
  foreground = "#FFE700"
  style = "plain"
  template = "{{ .HEAD }} "
  type = "git"

  [[blocks.segments]]
  foreground = "#43D426"
  style = "plain"
  template = "❯ "
  type = "text"

